server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaochao-ncp/spring-cloud-config.git  #配置github的https地址
          #读取分支
          search-paths:
          - spring-cloud-config
          #username: 475855186@qq.com 不用配置用户名和密码
          #password: gc475855186
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.0.104
    port: 5673
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/  #注册进eureka http://eureka7001:7001/eureka/
  instance:
    instance-id: config-center3344
    prefer-ip-address: true

#rabbitmq相关配置
rabbitmq:
  host: 192.168.0.104
  port: 15673
  username: guest
  password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
