server:
  port: 80

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka  #集群版
  instance:
    instance-id: consumerorder80
    prefer-ip-address: true

#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，两端连接所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个接口
    - com.floatpoint.springcloud.service.PaymentFeignService: debug
